package com.safecode.amber.bean;

public class articleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.a_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.u_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private Integer uId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.a_id
     *
     * @return the value of article.a_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.a_id
     *
     * @param aId the value for article.a_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.u_id
     *
     * @return the value of article.u_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.u_id
     *
     * @param uId the value for article.u_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }
}