package com.safecode.amber.bean;

public class article extends articleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.w_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private Integer wId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.w_title
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private String wTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.w_content
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private String wContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.w_id
     *
     * @return the value of article.w_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public Integer getwId() {
        return wId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.w_id
     *
     * @param wId the value for article.w_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setwId(Integer wId) {
        this.wId = wId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.w_title
     *
     * @return the value of article.w_title
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public String getwTitle() {
        return wTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.w_title
     *
     * @param wTitle the value for article.w_title
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setwTitle(String wTitle) {
        this.wTitle = wTitle == null ? null : wTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.w_content
     *
     * @return the value of article.w_content
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public String getwContent() {
        return wContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.w_content
     *
     * @param wContent the value for article.w_content
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setwContent(String wContent) {
        this.wContent = wContent == null ? null : wContent.trim();
    }
}