package com.safecode.amber.bean;

public class commentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.a_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.c_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private Integer cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.a_id
     *
     * @return the value of comment.a_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.a_id
     *
     * @param aId the value for comment.a_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.c_id
     *
     * @return the value of comment.c_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.c_id
     *
     * @param cId the value for comment.c_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }
}