package com.safecode.amber.bean;

import java.util.Date;

public class comment extends commentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.c_time
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.c_content
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private String cContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.c_time
     *
     * @return the value of comment.c_time
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.c_time
     *
     * @param cTime the value for comment.c_time
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.c_content
     *
     * @return the value of comment.c_content
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public String getcContent() {
        return cContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.c_content
     *
     * @param cContent the value for comment.c_content
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setcContent(String cContent) {
        this.cContent = cContent == null ? null : cContent.trim();
    }
}