package com.safecode.amber.bean;

public class users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_username
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private String uUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_pwd
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private String uPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_realname
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private String uRealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_email
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private String uEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_mobilenum
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    private String uMobilenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_id
     *
     * @return the value of users.u_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_id
     *
     * @param uId the value for users.u_id
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_username
     *
     * @return the value of users.u_username
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public String getuUsername() {
        return uUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_username
     *
     * @param uUsername the value for users.u_username
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setuUsername(String uUsername) {
        this.uUsername = uUsername == null ? null : uUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_pwd
     *
     * @return the value of users.u_pwd
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public String getuPwd() {
        return uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_pwd
     *
     * @param uPwd the value for users.u_pwd
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setuPwd(String uPwd) {
        this.uPwd = uPwd == null ? null : uPwd.trim();
    }

    @Override
    public String toString() {
        return "users{" +
                "uId=" + uId +
                ", uUsername='" + uUsername + '\'' +
                ", uPwd='" + uPwd + '\'' +
                ", uRealname='" + uRealname + '\'' +
                ", uEmail='" + uEmail + '\'' +
                ", uMobilenum='" + uMobilenum + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_realname
     *
     * @return the value of users.u_realname
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public String getuRealname() {
        return uRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_realname
     *
     * @param uRealname the value for users.u_realname
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setuRealname(String uRealname) {
        this.uRealname = uRealname == null ? null : uRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_email
     *
     * @return the value of users.u_email
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_email
     *
     * @param uEmail the value for users.u_email
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_mobilenum
     *
     * @return the value of users.u_mobilenum
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public String getuMobilenum() {
        return uMobilenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_mobilenum
     *
     * @param uMobilenum the value for users.u_mobilenum
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    public void setuMobilenum(String uMobilenum) {
        this.uMobilenum = uMobilenum == null ? null : uMobilenum.trim();
    }
}