package com.safecode.amber.dao;

import com.safecode.amber.bean.article;
import com.safecode.amber.bean.articleExample;
import com.safecode.amber.bean.articleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface articleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    long countByExample(articleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int deleteByExample(articleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int deleteByPrimaryKey(articleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int insert(article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int insertSelective(article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    List<article> selectByExample(articleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    article selectByPrimaryKey(articleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") article record, @Param("example") articleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByExample(@Param("record") article record, @Param("example") articleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByPrimaryKeySelective(article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByPrimaryKey(article record);
}