package com.safecode.amber.dao;

import com.safecode.amber.bean.comment;
import com.safecode.amber.bean.commentExample;
import com.safecode.amber.bean.commentKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface commentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    long countByExample(commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int deleteByExample(commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int deleteByPrimaryKey(commentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int insert(comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int insertSelective(comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    List<comment> selectByExample(commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    comment selectByPrimaryKey(commentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") comment record, @Param("example") commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByExample(@Param("record") comment record, @Param("example") commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByPrimaryKeySelective(comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon May 14 21:06:04 CST 2018
     */
    int updateByPrimaryKey(comment record);
}