package com.safecode.amber.dao;

import com.safecode.amber.bean.users;
import com.safecode.amber.bean.usersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface usersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    long countByExample(usersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int deleteByExample(usersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int deleteByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int insert(users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int insertSelective(users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    List<users> selectByExample(usersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    users selectByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") users record, @Param("example") usersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByExample(@Param("record") users record, @Param("example") usersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByPrimaryKeySelective(users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 14 21:06:03 CST 2018
     */
    int updateByPrimaryKey(users record);
}